### ISSUE TITLE
Use Project .babelrc From Storybook

### ISSUE THREAD

**Issue by Undistraction** [Mathspy/gatsby-storybook-jest-starter#6]
It looks like Storybook isn't using the `.babelrc` defined in the project root. I think you are defining a different set of babel plugins inside `storybook/webpack.config`. 

Wouldn't it make more sense to parse `babelrc` and use the plugins defined there?

My usecase is that I'm using styled-components and [babel-plugin-styled-components](https://www.styled-components.com/docs/tooling#better-debugging) which automatically generates a display name for components based on either the variable or file name. I have this defined in the project's `.babelrc`, however this isn't being used for components within storybook, meaning if I want to display their source within storybook it looks like: `<styled.div>` instead of `<VLayout>`.

**Comment by Mathspy** [comment]
It's relatively easy to add any plugin/preset into your storybook configuration:
```js
defaultConfig.module.rules[0].use[0].options.plugins = [
  require.resolve('@babel/plugin-proposal-class-properties'),
  require.resolve('babel-plugin-styled-components'),
]
```
The reasoning behind not using the default `.babelrc` is that there wasn't one to begin with (none comes with a Gatsby project) and I do realise overriding the settings in the way it's done is pretty hacky but that was kind of the intention. Duct tape fix storybook/babel integration until https://github.com/storybooks/storybook/pull/3746 is merge, which should be within the upcoming days 🎉 (thanks Storybook team!)
And at that point a `.babelrc` inside of root folder should [work perfectly fine](https://storybook.js.org/configurations/custom-babel-config/)

Side note: Sorry for getting back to you slowly had a relatively hectic week but should be available pretty consistently from now on!

**Comment by Undistraction** [comment]
Sure. I understand. I guess there are too many balls in the air until Gatsby v2 is final. I'll leave this open as it would make sense to use an existing `.babelrc` eventually.

**Comment by svict4** [comment]
Hey now that v2 is out, will the default `.babelrc` work fine with this starter?

**Comment by Mathspy** [comment]
Closing this as the `webpack.config` patching solution seems to be [the accepted solution by the Gatsby team](https://www.gatsbyjs.org/docs/visual-testing-with-storybook/) as well as the fact Gatsby is still being shipped with [uncompiled JSX](https://cdn.jsdelivr.net/npm/gatsby@2.1.30/cache-dir/gatsby-browser-entry.js) and [no easily accessible `webpack.config`](https://www.gatsbyjs.org/docs/add-custom-webpack-config/)

If this is really really needed though, it might be possible to still create a unified `.babelrc`/`babel.config.js` that both Storybook's custom config and Gatsby's could be manually configured using (by reading the config and adjusting Gatsby/Storybook through it)
